name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u your-dockerhub-username --password-stdin

    - name: Build Docker image
      run: docker build -t abolipatil2312/my-resume-image:latest .

    - name: Push Docker image
      run: docker push abolipatil2312/my-resume-image:latest